global:
  scrape_interval:     15s
  evaluation_interval: 15s

remote_write:
  - url: "http://localhost:9201/write"
remote_read:
  - url: "http://localhost:9201/read" 
    read_recent: true

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090','localhost:9000']

